AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  DynamoDB
  Sample SAM Template for DynamoDB and Indexes

Resources:
  dynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: movie
      AttributeDefinitions:
        - AttributeName: filmId
          AttributeType: N
        - AttributeName: title
          AttributeType: S
      KeySchema:
        - AttributeName: filmId
          KeyType: HASH
        - AttributeName: title
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
        - IndexName: gsi_movie_title
          KeySchema:
            - AttributeName: title
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
